<div id="content_left">
<?php
	echo $this->menuDepartamentos();
      
?>	
</div>

<div id="content_right">
<h1>Mis Contactos Personales del Departamento de <?php echo $this->departamento->getNombre(	) ?></h1>
<form method="post">
  <label>Mostrar Contactos por:</label>
  <select name="especialidad">
  	<option value="0">Todos</option>
  	<?php $especialidadDao = new App_Dao_EspecialidadDao();
  	foreach($especialidadDao->getTipo(App_Model_Especialidad::ESPECIALIDAD) as $especialidad) { ?>
  		<option value="<?php echo $especialidad->getId() ?>">
  			<?php echo $especialidad->getNombre(); ?>
  		</option>
  		<?php } //end foreach ?>
  </select>
  <label>Sub Especialidad:</label>
  <select name="subEspecialidad">
  	<option value="0">Todos</option>
  	<?php 
  	foreach($especialidadDao->getTipo(App_Model_Especialidad::SUBESPECIALIDAD) as $subEspecialidad) { ?>
  		<option value="<?php echo $subEspecialidad->getId() ?>">
  			<?php echo $subEspecialidad->getNombre() ?>
  		</option>
  	<?php } ?>
  </select>
  <input type="submit" value="Buscar" />
</form>
<br />
<?php if (Zend_Auth::getInstance()->getIdentity())  {?>	
    <p>
    <a href="<?php echo $this->baseUrl()?>/contacto/agregar">Nuevo Contacto</a>
    </p>
<?php  }?>
<table id="order_detail_table">
	<tr>
		<th>&nbsp;</th>
		<th>Nombre</th>
		<th>Telefonos</th>
		<th>Email</th>
                
        <?php if (Zend_Auth::getInstance()->getIdentity())  {?>
		<th>Acciones</th>
        <?php  }?>        
        
	</tr>
	<?php
		foreach($this->dataList as $contacto) {
	?>
	<tr>
		<td><?php if ($contacto->getFoto() != NULL) { ?>
				<img src="<?php echo stream_get_contents($contacto->getFoto()); ?>" width="60"/>
			<?php } else { ?>
				<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" width="60" />
			<?php }?>
			
		</td>
		<td>
			<a href='<?php echo $this->url(
					array(
						'controller' => 'contacto',
						'action'     => 'ver',
						'id'     => $contacto->getId(),
					), 'default', true) ?>'><?php echo $contacto->getNombres()."&nbsp;".$contacto->getApellidos();?></a>
		</td>
		<td>
			<?php
			foreach($contacto->getTelefonos() as $telefono) {
				if($telefono->getNumero()) {
					echo $telefono->getNumero() . '<br />';
				}
			}
			?>
		</td>
		<td> <?php echo $contacto->getEmail() ?></td>
                
   <?php if (Zend_Auth::getInstance()->getIdentity())  {?>
                
		<td>
			
			<a href='<?php echo $this->url(
					array(
						'controller' => 'contacto',
						'action'     => 'foto',
						'id'     => $contacto->getId(),
					), 'default', true); echo "'>";?><?php echo $contacto->getFoto()?"Modificar Foto":"Subir Foto"; ?></a>
				

			<a href='<?php echo $this->url(
					array(
						'controller' => 'contacto',
						'action'     => 'editar',
						'id'     => $contacto->getId(),
					), 'default', true) ?>'>Modificar</a>
				<a href='<?php echo $this->url(
					array(
						'controller' => 'contacto',
						'action'     => 'eliminar',
						'id'     => $contacto->getId(),
					), 'default', true) ?>'>Eliminar</a>
		</td>
                
                <?php  }?>
	</tr>
	<?php
	} // fin del foreach
	?>
</table>

<?php
echo $this->htmlPaginator;
?>
</div>
<!-- end of content right -->
<div class="cleaner_with_height">
	&nbsp;
</div>
