<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>
<div id="content_right">
 	<?php
			$contacto = $this->contacto;  
			$contacto;
			$depa = $contacto->getDepartamento();			
	?>	   
<h1>Detalle</h1>
<a href='<?php echo $this->url(	array(
				'controller' => 'contacto',
				'action'     => 'index',
				'departamento'=> $depa->getId(),
				), 'default', true) ?>'>Volver a mis Contactos</a>
<br />


	<h2>DATOS DEL CONTACTO </h2>	
		
		<br/>
		<div>
                    <div id="image_panel img">
						<?php if ($this->contacto->getFoto() != NULL) { ?>
							<img src="<?php echo stream_get_contents($this->contacto->getFoto()) ?>" />
						<?php } else { ?>
							<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
						<?php }?>
						
					</div>
		</div>		
<div id="detalle_acerca">
						
							<h2>Nombre:<?php  echo $this->contacto->getNombres()?></h2><br/>
							<h2>Apellidos: <?php echo $this->contacto->getApellidos(); ?></h2><br/>
							<div id="book_details">
							<ul>
							<?php $telefonos = $this->contacto->getTelefonos();
							foreach($telefonos as $telefono) {
								echo $telefono->getTipo() . ": " . $telefono->getNumero() . "<br/>";
							}
							?><br/>
							Especialidad: <?php echo $this->contacto->getEspecialidad()->getNombre(); ?><br/>
							Sub-especialidad: <?php echo $this->contacto->getSubespecialidad()->getNombre(); ?><br/>
							Correo electronico: <?php echo $this->contacto->getEmail();?><br/>     
							Dirección: <?php echo $this->contacto->getDireccion();?><br/>
							</ul>
							</div>
						
					</div>
</div>