<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>

<h1>Detalle</h1>
<?php
	echo "mi nombre es: " . $this->contacto->getNombres(); 
	echo "Mi apellido es:" . $this->contacto->getApellidos();
?>
	<?php
			$contacto = $this->contacto;  
			$contacto;
			
	?>
	<h2><?php echo $this->contacto->getNombres();  $this->contacto->getApellidos();?></h2>
	<h2>DATOS DEL CLIENTE </h2>
		
		
		<br/>
		<div id="image_panel">
						<?php if ($this->contacto->getFoto() != NULL) { ?>
							<img src="<?php echo stream_get_contents($this->contacto->getFoto()); ?>" alt="image" />
						<?php } else { ?>
							<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
						<?php }?>
						
					</div>
					
<div id="detalle_contacto">
						<ul>
							Nombre:<?php  echo $this->contacto->getNombres()?><br/>
							Apellidos: <?php echo $this->contacto->getApellidos(); ?><br/>
							<?php $telefonos = $this->contacto->getTelefonos();
							foreach($telefonos as $telefono) {
								echo $telefono->getTipo() . ": " . $telefono->getNumero() . "<br/>";
							}
							?><br/>
							Especialidad: <?php echo $this->contacto->getEspecialidad()->getNombre(); ?><br/>
							Sub-especialidad: <?php echo $this->contacto->getSubespecialidad()->getNombre(); ?><br/>
							Correo electronico: <?php echo $this->contacto->getEmail();?><br/>
							Dirección: <?php echo $this->contacto->getDireccion();?><br/>
						</ul>
					</div>
