<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>
<div id="content_right">
    
<h1>QUIENES SOMOS ...</h1>
		
	<h2>Guia Médica </h2>	
		
		
		<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        Somos  bla bla bla bla 
        
        bla bla bla bla        bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla         bla bla bla bla 
        bla bla bla bla bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                
    </p>
   </div>
</div>
<div id="content_right">
    <br/>
<h1>MISION</h1>
		
	<h2>Guia Médica </h2>	
		
		<br/>
		<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        Somos  bla bla bla bla 
        
        bla bla bla bla        bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla         bla bla bla bla 
        bla bla bla bla bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                
    </p>
   </div>
</div>

<div id="content_right">
    <br/>
<h1>VISION</h1>
		
	<h2>Guia Médica </h2>	
		
		<br/>
		<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        Somos  bla bla bla bla 
        
        bla bla bla bla        bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla         bla bla bla bla 
        bla bla bla bla bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                
    </p>
   </div>
</div>