<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>
<div id="content_right">
    
<h1>QUIENES SOMOS</h1>
		
	<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        <?php echo "" ?>
    </p>
   </div>
   <a href="<?php echo $this->url(
					array(
						'controller' => 'index',
						'action'     => 'modificar',
						'nombre'	 => 'somos'						
						), 'default', true) ?>">Modificar...</a>
</div>

<div id="content_right">
    <br/>
<h1>MISION</h1>
				
		<br/>
		<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
       <?php echo "" ?>
    </p>
   </div>
   <a href="<?php echo $this->url(
					array(
						'controller' => 'index',
						'action'     => 'modificar',
						'nombre'	 => 'mision'						
						), 'default', true) ?>">Modificar...</a>
</div>

<div id="content_right">
    <br/>
<h1>VISION</h1>
		<br/>
		<div id="image_about">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        <?php echo ""; ?>
    </p>
   </div>
   <a href="<?php echo $this->url(
					array(
						'controller' => 'index',
						'action'     => 'modificar',
						'nombre'	 => 'vision'						
						), 'default', true) ?>">Modificar...</a>
</div>
<div class="cleaner_with_height">
	&nbsp;
</div>