<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>
<div id="content_right">
    
<h1>MISIÓN</h1>
		
	<div id="image_about">
                    <div id="image_panel img"
                       <img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" />  
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        Somos un grupo de profesionales altamente calificados que ofrecemos servicios de salud, reunimos a los médicos más reconocidos y especializados dentro de una agenda medica nacional. con altos estándares de calidad, tecnología de vanguardia y apego a las más estrictas normas de seguridad, ética y valores; para otorgar una atención humanística y efectiva en los resultados del servicio, satisfaciendo las necesidades y expectativas de lo más importante que son, nuestros pacientes.
Buscamos poner al alcance de las manos de los pacientes un abanico de médicos especialistas y áreas de medicina para que el paciente pueda  elegir el que mejor para su necesidad. 
El paciente tendrá en su celular o equipo con tecnología androide el único DIRECTORIO MEDICO BOLIVIA y sin conexión a internet, todo en una sola app.

    </p>
   </div>
   
</div>

<div id="content_right">
    <br/>
<h1>VISIÓN</h1>
				
		<br/>
		<div id="image_vision">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
       Ser una empresa líder en el área de la salud por su excelente reconocimiento y confianza en la sociedad médica y civil en el noroeste de México.
Realizar acuerdos con todos los colegios medicos de todo Bolivia y de esta manera tener en una sola aplicación android  a todos los medicos y profecionales en salud ademas de las instituciones con alcanze nacional para la comodidad de los pacientes que buscan una herramienta que le brinde un abanico de oportunidades con respecto a la busqueda de su salud.

    </p>
   </div>
  
</div>

<div id="content_right">
    <br/>
<h1>VALORES</h1>
		<br/>
		<div id="image_valores">
                    <div id="image_panel img"	
                         <img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        
♦ acercar al médico con la ciudadanía en General<br />
♦ Atención medica satisfactoria.<br />
♦ Actitud de servicio.<br />
♦ Primero es el cliente.<br />
♦ Escuchamos sus necesidades.<br />
♦ Confiabilidad en los médicos colegiados.<br />
♦ Calidad en salud de los mejores profesionales<br />

    </p>
   </div>
  
</div>
