<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>

<div id="content_right">
    <br/>	
    <h1>CONTACTANOS</h1>
    <br/>
    <h2>Agenda Médica Bolivia </h2>	
		
		
		<div id="image_contacto">
                    <div id="image_panel img" </div>
		</div>		
<div id="detalle_contactenos">
	<br />					
    <p>
        Para contactarse con los administradores,<br />
        agregar su información y ser parte de<br />
        la Agenda Medica Bolivia o para obtener la app<br />
        para dispositivos moviles comuniquese con:<br />
        ♦Telefonos:<br />
        ♦Email:
    </p>
   </div>
        </div>
    </div>