<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>


<h1>CONTACTANOS</h1>
		
	<h2>Guia Médica </h2>	
		
		
		<div id="image_panel">
                    <div id="image_panel img"
			<img src="<?php echo $this->baseUrl() . "/images/no_cover.jpg"; ?>" alt="image" />
                    </div>
		</div>		
<div id="detalle_acerca">
						
    <p>
        Somos  bla bla bla bla 
        
        bla bla bla bla        bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla         bla bla bla bla 
        bla bla bla bla bla bla bla bla 
        bla bla bla bla         bla bla bla bla 
        bla bla bla bla         bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla 
                
    </p>
   </div>