<div id="content_left">
<?php
	echo $this->menuForm();
       
?>	
</div>
<div id="content_right">
<h1>Especialidades y Sub-Especialidades</h1>
<?php
	echo $this->form;
?>
<table id="order_detail_table">
	<tr>
		<th>Nombre</th>
		<th>Tipo</th>
		<th>Acciones</th>
	</tr>
	<?php
		foreach($this->especialidades as $especialidad) {
	?>
	<tr>
		<td><?php echo $especialidad->getNombre(); ?></td>
		<td><?php echo $especialidad->getTipo(); ?></td>
		<td>
                    <a href='<?php echo $this->url(
					array(
						'controller' => 'especialidad',
						'action'     => 'editar',
						'id'     => $especialidad->getId(),
					), 'default', true) ?>'>Modificar</a>
                    <a href='<?php echo $this->url(
					array(
						'controller' => 'especialidad',
						'action'     => 'eliminar',
						'id'     => $especialidad->getId(),
					), 'default', true) ?>'>Eliminar</a>
			
		</td>
	</tr>
	<?php }//fin del foreach ?>
</table>
</div>