<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>		
</div>
<div id="content_right">
<h1>Instituciones de la ciudad de <?php //echo $this->departamento->getNombre() ?> </h1>
<?php
	echo $this->form;
?>
<table id="order_detail_table">
	<tr>
		<th>Nombre</th>
		
		<th>Acciones</th>
	</tr>
	<?php
		foreach($this->especialidades as $especialidad) {
	?>
	<tr>
		<td><?php echo $especialidad->getNombre(); ?></td>
		<td>
			
		</td>
	</tr>
	<?php }//fin del foreach ?>
</table>
</div>