<div id="content_left">
<?php
	echo $this->menuDepartamentos();
?>	
</div>
<div id="content_right">
<h1>Mis Instituciones de <?php echo $this->departamento->getNombre() ?> - Categoria <?php  echo $this->categoria->getNombre(); ?></h1>
<form method="post">
  <label>Mostrar Contactos por:</label>
  <select name="especialidad">
  	<?php $especialidadDao = new App_Dao_EspecialidadDao();
  	foreach($especialidadDao->getTodos() as $especialidad) { ?>
  		<option value="<?php echo $especialidad->getId() ?>">
  			<?php echo $especialidad->getNombre(); ?>
  		</option>
  		<?php } //end foreach ?>
  </select>
  <input type="submit" value="Buscar" />
</form>
<?php if (Zend_Auth::getInstance()->getIdentity())  {?>		
<p><a href="<?php echo $this->url(
					array(
						'controller' => 'entidad',
						'action'     => 'agregar',
						'id'     => $this->categoria->getId(),
                       'departamento'=>$this->departamento->getId(),

					), 'default', true) ?>">Nuevo</a></p>
<?php } //end conditional auth ?>
<table id="order_detail_table">
	<tr>
		<th>Nombre</th>
		<th>Telefono</th>
		<th>Encargado</th>
<?php if (Zend_Auth::getInstance()->getIdentity())  {?>			
		<th>Acciones</th>
<?php } ?>
	</tr>
	<?php foreach($this->entidades as $entidad) { ?>
	<tr>
		<td>
			<a href='<?php echo $this->url(
					array(
						'controller' => 'entidad',
						'action'     => 'ver',
						'id'     => $entidad->getId(),
					), 'default', true) ?>'><?php echo $entidad->getNombre();?></a>
		</td>
		<td><?php echo $entidad->getTelefono()->getNumero(); ?></td>
		<td><?php echo $entidad->getEncargado(); ?></td>
<?php if (Zend_Auth::getInstance()->getIdentity())  {?>	                
                <td>
                    <a href='<?php echo $this->url(
					array(
						'controller' => 'entidad',
						'action'     => 'editar',
						'id'     => $entidad->getId(),
					), 'default', true) ?>'>Modificar</a>
				<a href='<?php echo $this->url(
					array(
						'controller' => 'entidad',
						'action'     => 'eliminar',
						'id'     => $entidad->getId(),
					), 'default', true) ?>'>Eliminar</a>
                </td>
    <?php } ?>
	</tr>		
	<?php } //fin del foreach ?>	
</table>
<?php
echo $this->htmlPaginator; 
?>
</div>
<div class="cleaner_with_height">
	&nbsp;
</div>