<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Agenda Medica Bolivia');

echo $this->doctype();
$session = new Zend_Session_Namespace('systemSession');
/**
 * @var App_Model_Order
 */
$order = unserialize($session->cart);
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
    		<?php echo $this->headMeta(); ?>
    		<?php echo $this->headTitle(); ?>
    		<meta name="keywords" content="agenda, medicos, cochabamba, web" />
    		<meta name="description" content="Sistema Web Para la administración de Contactos e Intituciones Medicas" />
    		
    		<?php
			echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/humanity/jquery-ui-1.10.3.custom.min.css');
			echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css');
			echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.simplyscroll.css');
			echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery.jqplot.min.css');

			echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-1.10.2.min.js', 'text/javascript');
			echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.cycle.all.js', 'text/javascript');
			echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui-1.10.3.custom.min.js', 'text/javascript');
			echo $this->headScript()->appendFile($this->baseUrl() . '/js/custom_scripts.js', 'text/javascript');
			echo $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.jqplot.min.js', 'text/javascript');
			echo $this->headScript()->appendFile($this->baseUrl() . '/js/jqplot.categoryAxisRenderer.min.js', 'text/javascript');
    		?>
	</head>
	<body>
	
            
		<div id="container">
                    
			<div id="before-header">
                            
				
                      <div id="header">
				<div id="main_logo">
					
				</div>
				
			

			</div>
                          <div id="menu">
					<ul>
						<li>
							<a class="current"></a>
                                                        
						</li>
						
					</ul>
					
				</div>
			<!-- end of header -->

			<div id="content">
					<?php echo $this->layout()->content; ?>
			</div>
			<!-- end of content -->

			<div id="footer">
				Copyright (R) 2014 <strong> Agenda Medica</strong> | Website Templates by <a </a>
			</div>
			<!-- end of footer -->
			
		</div>
		<!-- end of container -->
	</body>
</html>